---
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted